<?php

$labels = array();

$labels['forwarding'] = 'Weiterleitung';
$labels['editforwarding'] = 'Weiterleitung bearbeiten';

$labels['enabled'] = 'Aktiviert';
$labels['address'] = 'Adresse';
$labels['keeporiginalmessage'] = 'Originale Nachricht behalten';

$messages = array();
$messages['novalidemailaddress'] = 'Keine gültige E-Mail-Adresse.';
$messages['successfullyupdated'] = 'Weiterleitung erfolgreich aktualisiert.';
$messages['internalerror'] = 'Fehler bei der ausgewählten Aktion.';
//$messages['connecterror'] = $messages['internalerror'] . ' Connection error.';
$messages['loaderror'] = 'Weiterleitung konnte nicht geladen werden.';
$messages['loadconnecterror'] = $messages['loadinternalerror'] . ' Connection error.';
$messages['updateerror'] = 'Weiterleitung konnte nicht aktualisiert werden.';
$messages['updateconnecterror'] = $messages['updateerror'] . ' Connection error.';
