<?php

$labels['forwarding'] = 'Vidarebefodring';
$labels['editforwarding'] = 'Ändra vidarebefodring';

$labels['enabled'] = 'Aktiv';
$labels['address'] = 'Adress';
$labels['keeporiginalmessage'] = 'Behåll orginalmeddelandet';

$messages['successfullyupdated'] = 'Vidarebefodringen har uppdaterats.';
$messages['internalerror'] = 'Fel uppstod i vald åtgärd.';
//$messages['connecterror'] = $messages['internalerror'] . ' Uppkopplingsfel.';
$messages['loaderror'] = 'Kunde inte ladda vidarebefodringen.';
$messages['loadconnecterror'] = $messages['loadinternalerror'] . ' Uppkopplingsfel.';
$messages['updateerror'] = 'Kunde inte uppdatera vidarebefodringen.';
$messages['updateconnecterror'] = $messages['updateerror'] . ' Connection error.';
